# Generated by Django 4.1.5 on 2023-01-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speech_rec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speechfilemodel',
            old_name='extensions',
            new_name='extension',
        ),
    ]
